### ISSUE TITLE
poetry installed with install-poetry.py does not respect asdf python version

### ISSUE THREAD

**Issue by shawon-crosen** [asdf-community/asdf-poetry#10]
Due to the way poetry is installed by asdf and the way that poetry decides which python verion it should use, it is only able to use the version of python that is created as a venv in it's install path when it is installed. 

Example:
Set asdf to use python 3.8.7 globally
```
wintermute:~/CircleCi/Github/dbt-data-modeling:(fix_cves_8_05)> asdf global python 3.8.7
wintermute:~/CircleCi/Github/dbt-data-modeling:(fix_cves_8_05)> python --version
Python 3.8.7
```

Output during `poetry install` with python version specified as "^3.8" in pyproject.toml:
```
Creating virtualenv dbt-data-modeling-5cvI_FFT-py3.9 in /Users/shawon/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/shawon/Library/Caches/pypoetry/virtualenvs/dbt-data-modeling-5cvI_FFT-py3.9
```

Output of `poetry env`:
```
Poetry
Version: 1.1.7
Python:  3.9.6

Virtualenv
Python:         3.9.6
Implementation: CPython
Path:           NA

System
Platform: darwin
OS:       posix
Python:   /Users/shawon/.asdf/installs/poetry/1.1.7/venv
```

I believe this is related to this issue, specifically the comment by finswimmer: https://github.com/python-poetry/poetry/issues/1888

**Comment by crflynn** [comment]
This seems like an issue with the new installer provided by poetry. The issue is discussed here:

* https://github.com/python-poetry/poetry/issues/4199
* https://github.com/python-poetry/poetry/issues/651#issuecomment-864533910 <- explanation
* https://github.com/python-poetry/poetry/issues/4187#issuecomment-863881765 <- more explanation

I don't know if there is an easy workaround here until they resolve this (if they choose to), but it unfortunately breaks the way we use poetry with asdf.

We could go back to the old installer, and this problem would go away. However we wouldn't be able to use 1.2+ versions of poetry, and the old installer is planned to be deprecated.

I don't think there is much we can easily do here unless poetry changes the way it is installed.

**Comment by shawon-crosen** [comment]
That makes sense, thank you for the thorough response! 

Bummer that the installer changed that, I really liked being able to have different poetry versions available via asdf. 

My workaround for now is to install poetry with the script, then just point it to the correct python asdf version by running `poetry env $ASDF_INSTALL_PATH/python`. That works for now.

Feel free to close this if you'd like, I understand this is pretty much out of your hands.

**Comment by crflynn** [comment]
I'm wondering if we can incorporate some workaround here to have it use the asdf specified version of python. Otherwise I'm considering using the old installer until it is fully deprecated.

**Comment by crflynn** [comment]
@smorimoto if I could ask for some bash help I wonder if we can conditionally install with the legacy `get-poetry.py` if ASDF_INSTALL_VERSION <1.2.0 and use the new `install-poetry.py` otherwise.

**Comment by Kurt-von-Laven** [comment]
The maintainers of Poetry recently pointed out (c.f., [#3345](https://github.com/python-poetry/poetry/issues/3345#issuecomment-974640376)) that they have since resolved this issue on `master`, but the fix ([#4433](https://github.com/python-poetry/poetry/pull/4433)) has not yet been released. Look for it on `poetry > 1.2.0a2` once that is released. At that time, I believe this plugin will be able to stop using the deprecated `get-poetry.py` even for `poetry < 1.2`.

**Comment by tony** [comment]
I don't fully understand the issue yet, but if we're receiving the `ModuleNotFoundError: No module named 'cleo' ` when using python 3.10 and using the `poetry` command, I assume this would be the appropriate issue to monitor?

```
curl -sSL https://install.python-poetry.org | python -
```

If I understand correctly, we can now use:

https://install.python-poetry.org

In place of the URL at https://github.com/asdf-community/asdf-poetry/blob/6176ff26132170c74a9daf1044e7d5ac62fe7546/bin/install#L37.

As the installer project is now independent of poetry releases: https://github.com/python-poetry/install.python-poetry.org

**Comment by tony** [comment]
If we're receiving `ModuleNotFoundError: No module named 'cleo' ` the new installer fixes it for me.  It operates outside the normal releases of poetry in a new repo.

```
curl -sSL https://install.python-poetry.org | python -
```

If I understand correctly, we can now use:

https://install.python-poetry.org

In place of the URL at https://github.com/asdf-community/asdf-poetry/blob/6176ff26132170c74a9daf1044e7d5ac62fe7546/bin/install#L37.

As the installer project is now independent of poetry releases: https://github.com/python-poetry/install.python-poetry.org

PR at #15

**Comment by Kurt-von-Laven** [comment]
There is now [an open PR](https://github.com/python-poetry/poetry/pull/4852) proposing the addition of a setting that would allow the installation of Poetry using the current version of Python. The author, @finswimmer, is asking for feedback. Would there be any concerns with using such an option to install Poetry in this asdf plugin?

**Comment by tony** [comment]
I've did a test with `.python-version` in a repo, looks good

My default system python is `3.7.9` but when inside the repo, `python` correctly shows as `3.10.0`

```
~ ❯ python -V
Python 3.7.9
~ ❯ cd ~/projects/project-with-3.10
❯ python -V
Python 3.10.0
```

**Comment by tony** [comment]
@Kurt-von-Laven On a separate note, in the issue you are testing with 1.1.7 (where I still get the error)

if you use `poetry 1.1.11` and have `.python-version` set in your projects, does it obey the python version?

In my testing this is working, but I've installed via this: `ASDF_POETRY_INSTALL_URL=https://install.python-poetry.org asdf install poetry 1.1.11`

How does it work then?

(It's difficult to track all the issues between this and poetry's tracker, so trying to get an idea what's working and what's not as of now)

**Comment by Kurt-von-Laven** [comment]
@tony, sorry I completely missed this. I am using `.tool-versions` rather than `.python-version`, although I don't think the distinction is salient to any of the issues at hand. I updated to asdf v0.9.0 and reinstalled the latest version of the asdf-poetry plugin. I see the expected version of Python (from `.tool-versions`) using both `poetry 1.1.7` and `poetry 1.1.11`. I didn't even have to use `ASDF_POETRY_INSTALL_URL`. I wonder if asdf-poetry is already using the setting introduced by [the aforementioned PR](https://github.com/python-poetry/poetry/pull/4852)?

**Comment by crflynn** [comment]
This is fixed by https://github.com/asdf-community/asdf-poetry/pull/21, though only for poetry 1.2+.

**Comment by mwdiers** [comment]
On the latest version of asdf (0.11.1) and poetry (1.3.2), this is still a problem. The local python version is ignored by poetry unless I create the environment with `poetry env use $(asdf which python)`

**Comment by Kurt-von-Laven** [comment]
Are you able to reproduce the issue after uninstalling Poetry and then reinstalling it while the desired version of Python is active? The local Python version at the time of installation is the one that is used, but it doesn't automatically update.

**Comment by SergiyKolesnikov** [comment]
> Are you able to reproduce the issue after uninstalling Poetry and then reinstalling it while the desired version of Python is active? The local Python version at the time of installation is the one that is used, but it doesn't automatically update.

Is it possible to install poetry once and make it respect the local Python version set by asdf? Otherwise, since different projects my require different Python versions, poetry will have to be reinstalled every time I want to work on a different project.

**Comment by SergiyKolesnikov** [comment]
> On the latest version of asdf (0.11.1) and poetry (1.3.2), this is still a problem. The local python version is ignored by poetry unless I create the environment with `poetry env use $(asdf which python)`

Setting the [virtualenvsprefer-active-python-experimental](https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental) to `true` (e.g., in your shell's rc file) will make poetry respect the currently active version of Python. So, my current workflow looks something like this:
```
mkdir project-dir
cd project-dir
asdf local python 3.10.9   # change to the required Python version
poetry init
```

Thanks to @finswimmer for posting this https://github.com/python-poetry/poetry/issues/1888#issuecomment-1250362817
